# This file was generated by GoReleaser. DO NOT EDIT.
cask "fuzzy-repo-finder" do
  version "2.4.0"

  on_macos do
    on_intel do
      sha256 "09e14141f743da16b480138d1b323636787adc2530ae8b8a803f30771cdab1ac"
      url "https://github.com/hoto/fuzzy-repo-finder/releases/download/#{version}/fuzzy-repo-finder_Darwin_x86_64.zip"
    end
    on_arm do
      sha256 "06a991770d9304a87c42a32a7cfa3773b1a9a781c33d61dc569f868def2a3908"
      url "https://github.com/hoto/fuzzy-repo-finder/releases/download/#{version}/fuzzy-repo-finder_Darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "89e790512c78719ec6da24a0ea392e5322975513701a9551156225e850f87e3b"
      url "https://github.com/hoto/fuzzy-repo-finder/releases/download/#{version}/fuzzy-repo-finder_Linux_x86_64.zip"
    end
    on_arm do
      sha256 "bd27f9be6b5b7c98efb53c53794946ce6ad1b58cd2e704a5cfc450ae15ba2527"
      url "https://github.com/hoto/fuzzy-repo-finder/releases/download/#{version}/fuzzy-repo-finder_Linux_arm64.zip"
    end
  end

  name "fuzzy-repo-finder"
  desc "Navigate locally cloned repos."
  homepage "https://github.com/hoto/fuzzy-repo-finder"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fuzzy-repo-finder"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fuzzy-repo-finder"]
    end
  end

  # No zap stanza required

end
