# This file was generated by GoReleaser. DO NOT EDIT.
cask "fuzzy-repo-finder" do
  version "2.3.0"

  on_macos do
    on_intel do
      sha256 "4374335ed0f04a5b5e0c3793e07b79b6b17f377b12c98f64e1b24a77d3de114c"
      url "https://github.com/hoto/fuzzy-repo-finder/releases/download/#{version}/fuzzy-repo-finder_Darwin_x86_64.zip"
    end
    on_arm do
      sha256 "d6711249278c5026bd699104b7da7597f0fbd799d51a168aa3c32e3c4a922b20"
      url "https://github.com/hoto/fuzzy-repo-finder/releases/download/#{version}/fuzzy-repo-finder_Darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "eeb633704d8656c94d1c92ebcb9d7e73e64f017480b35f3eb762d12f72135a0c"
      url "https://github.com/hoto/fuzzy-repo-finder/releases/download/#{version}/fuzzy-repo-finder_Linux_x86_64.zip"
    end
    on_arm do
      sha256 "bbda46c97d652040f1765f10d1494e3a96ea54ae859a845aa5b70392230d5545"
      url "https://github.com/hoto/fuzzy-repo-finder/releases/download/#{version}/fuzzy-repo-finder_Linux_arm64.zip"
    end
  end

  name "fuzzy-repo-finder"
  desc "Navigate locally cloned repos."
  homepage "https://github.com/hoto/fuzzy-repo-finder"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fuzzy-repo-finder"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fuzzy-repo-finder"]
    end
  end

  # No zap stanza required

end
