# This file was generated by GoReleaser. DO NOT EDIT.
class GitMyGit < Formula
  desc "Navigitae locally cloned repos."
  homepage "https://github.com/hoto/git-my-git"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hoto/git-my-git/releases/download/0.0.3/git-my-git_Darwin_x86_64.zip"
    sha256 "bb2caae66ce1f484c7efcb405f708c0af796ad2a549a1c8e954e5d784970c59c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hoto/git-my-git/releases/download/0.0.3/git-my-git_Linux_x86_64.zip"
      sha256 "8d6e3095361f659507a5ac118b3b50bcc50d93fd3a0c05957309137657d3b91d"
    end
  end

  def install
    bin.install "git-my-git"
  end

  test do
    system "#{bin}/git-my-git --version"
  end
end
