# This file was generated by GoReleaser. DO NOT EDIT.
class GitMyGit < Formula
  desc "Navigitae locally cloned repos."
  homepage "https://github.com/hoto/git-my-git"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hoto/git-my-git/releases/download/0.0.2/git-my-git_Darwin_x86_64.zip"
    sha256 "7f20ad22c3c52f2cf90da57caeceb15c5255ddf5b1d966866cb54b0d0eb5d69d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hoto/git-my-git/releases/download/0.0.2/git-my-git_Linux_x86_64.zip"
      sha256 "a4987bfaf2012daa3410637bd3cee03871313d950993ddea0da95615447aba46"
    end
  end

  def install
    bin.install "git-my-git"
  end

  test do
    system "#{bin}/git-my-git --version"
  end
end
