# This file was generated by GoReleaser. DO NOT EDIT.
class GitMyGit < Formula
  desc "Navigitae locally cloned repos."
  homepage "https://github.com/hoto/git-my-git"
  version "1.0.11"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hoto/git-my-git/releases/download/1.0.11/git-my-git_Darwin_x86_64.zip"
    sha256 "b2733478ee767298d97bfac19ad739c58b3fe494accf20345f3d1fa6b3ee9ac4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hoto/git-my-git/releases/download/1.0.11/git-my-git_Linux_x86_64.zip"
      sha256 "51703f0677a465ea03ca7a1f68d086d4051e588b219e09113077e3ea887c34d9"
    end
  end

  def install
    bin.install "git-my-git"
  end

  test do
    system "#{bin}/git-my-git --version"
  end
end
