# This file was generated by GoReleaser. DO NOT EDIT.
class JenkinsCredentialsDecryptor < Formula
  desc "Navigitae locally cloned repos."
  homepage "https://github.com/hoto/jenkins-credentials-decryptor"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hoto/jenkins-credentials-decryptor/releases/download/1.1.0/jenkins-credentials-decryptor_Darwin_x86_64.zip"
    sha256 "15e18b06720c468ade91feb83c2a61b64cbaf59969cd457e4cecd99f6e008a26"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hoto/jenkins-credentials-decryptor/releases/download/1.1.0/jenkins-credentials-decryptor_Linux_x86_64.zip"
      sha256 "fa0ef061ead425d89484f367e813d77400bffb725664f92057b7da6a132797bf"
    end
  end

  def install
    bin.install "jenkins-credentials-decryptor"
  end

  test do
    system "#{bin}/jenkins-credentials-decryptor --version"
  end
end
