# This file was generated by GoReleaser. DO NOT EDIT.
class JenkinsCredentialsDecryptor < Formula
  desc "Navigitae locally cloned repos."
  homepage "https://github.com/hoto/jenkins-credentials-decryptor"
  version "0.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hoto/jenkins-credentials-decryptor/releases/download/0.0.9/jenkins-credentials-decryptor_Darwin_x86_64.zip"
    sha256 "12123ae0a7c75208d8127ad0777da519366149f3127a53c27f52e0b82d1a697e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hoto/jenkins-credentials-decryptor/releases/download/0.0.9/jenkins-credentials-decryptor_Linux_x86_64.zip"
      sha256 "a8780e6dfc3bd17937064e3ca0d1bcdf97bf0ff775073fa4eeb472adb4a6a6eb"
    end
  end

  def install
    bin.install "jenkins-credentials-decryptor"
  end

  test do
    system "#{bin}/jenkins-credentials-decryptor --version"
  end
end
