# This file was generated by GoReleaser. DO NOT EDIT.
class TemplateGoCli < Formula
  desc "Golang CLI template."
  homepage "https://github.com/hoto/template-go-cli"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/hoto/template-go-cli/releases/download/1.0.0/template-go-cli_Darwin_x86_64.zip"
    sha256 "a44e2f28cfd56d0624cb8251a6e069adc750b927525abbbc705b66170845fc5c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/hoto/template-go-cli/releases/download/1.0.0/template-go-cli_Linux_x86_64.zip"
      sha256 "baca741cbae155a3dfc153f9f23782a268c6bf24b8b927cc7d0defd85e7e65d5"
    end
  end

  def install
    bin.install "template-go-cli"
  end

  test do
    system "#{bin}/template-go-cli --version"
  end
end
