# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TemplateGoCli < Formula
  desc "Golang CLI template."
  homepage "https://github.com/hoto/template-go-cli"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hoto/template-go-cli/releases/download/1.0.3/template-go-cli_Darwin_x86_64.zip"
      sha256 "ae8a3c1d40ff9d94356b1e01645b4e054e9c2e93dad6d9f501ee47ef1d587276"

      def install
        bin.install "template-go-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hoto/template-go-cli/releases/download/1.0.3/template-go-cli_Darwin_arm64.zip"
      sha256 "933a4f0ece12174faf14cef3eeec8f02737629241e7f0d1dde05624c4170f992"

      def install
        bin.install "template-go-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hoto/template-go-cli/releases/download/1.0.3/template-go-cli_Linux_arm64.zip"
      sha256 "a9434066ba6ae440beee83c0548364bac77f214ace88077fe5db79fec16e2840"

      def install
        bin.install "template-go-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hoto/template-go-cli/releases/download/1.0.3/template-go-cli_Linux_x86_64.zip"
      sha256 "099b67a4ff58d0d6a271b7572e81cf31c12fc18b980bd5f4460bebe28e2a085c"

      def install
        bin.install "template-go-cli"
      end
    end
  end

  test do
    system "#{bin}/template-go-cli --version"
  end
end
